"""Hand-curated filler word banks used by the phrase builder.

Two lists:

* :data:`DETERMINERS` - articles, possessives, and quantifiers that sit
  at the start of a noun phrase (``the``, ``some``, ``every``, …).
  Both ``"a"`` and ``"an"`` are included because
  :func:`rhymepass.phrases._pick_determiner` upgrades ``"a"`` to
  ``"an"`` when the following word begins with a vowel sound.

* :data:`ADJECTIVES` - generic positive/neutral adjectives suitable for
  modifying almost any noun (``nimble``, ``radiant``, ``zesty``, …).

Conventions for entries in both lists:

* all lower-case,
* alphabetical within each list,
* no duplicates,
* no multi-word entries, no punctuation, no proper nouns.

These banks are deliberately modest in size to keep the output
readable. If you add entries, keep the tone light and inclusive, and
avoid anything that would be hard to type or spell aloud.
"""

from __future__ import annotations

DETERMINERS: list[str] = [
    "a",
    "all",
    "another",
    "any",
    "both",
    "certain",
    "each",
    "either",
    "every",
    "few",
    "half",
    "its",
    "many",
    "most",
    "much",
    "my",
    "neither",
    "no",
    "one",
    "our",
    "several",
    "some",
    "such",
    "that",
    "the",
    "these",
    "this",
    "those",
    "various",
    "what",
    "which",
    "whose",
    "your",
]

ADJECTIVES: list[str] = [
    "abundant",
    "agile",
    "airy",
    "amber",
    "bold",
    "breezy",
    "brisk",
    "bronze",
    "calm",
    "candid",
    "careful",
    "cheerful",
    "dapper",
    "daring",
    "dauntless",
    "deft",
    "dynamic",
    "eager",
    "earnest",
    "earthy",
    "ebullient",
    "electric",
    "fabled",
    "faithful",
    "fancy",
    "fearless",
    "fertile",
    "gentle",
    "gilded",
    "graceful",
    "grand",
    "gritty",
    "happy",
    "hardy",
    "harmonic",
    "hazy",
    "hopeful",
    "icy",
    "ideal",
    "immense",
    "impish",
    "intricate",
    "jaunty",
    "jazzy",
    "jolly",
    "judicious",
    "just",
    "keen",
    "kind",
    "kinetic",
    "knowing",
    "lively",
    "lucid",
    "lucky",
    "lush",
    "lyrical",
    "magnetic",
    "mellow",
    "mindful",
    "misty",
    "modern",
    "nifty",
    "nimble",
    "noble",
    "nuanced",
    "open",
    "opulent",
    "orderly",
    "organic",
    "outgoing",
    "patient",
    "playful",
    "poised",
    "polished",
    "primal",
    "quick",
    "quiet",
    "quintessential",
    "quirky",
    "radiant",
    "rapid",
    "rare",
    "refined",
    "robust",
    "sable",
    "sage",
    "serene",
    "sharp",
    "steady",
    "tactile",
    "tidy",
    "timely",
    "tranquil",
    "trusty",
    "upbeat",
    "urbane",
    "useful",
    "utopian",
    "valiant",
    "vast",
    "vibrant",
    "vigilant",
    "vital",
    "warm",
    "watchful",
    "weightless",
    "wild",
    "witty",
    "xenial",
    "xeric",
    "yare",
    "yearning",
    "yielding",
    "youthful",
    "zany",
    "zealous",
    "zen",
    "zesty",
]
