name: ci

on:
  push:
  workflow_call:

permissions:
  contents: read

jobs:
  ci:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trunk check
        uses: trunk-io/trunk-action@v1

      - name: Install mise
        uses: jdx/mise-action@v2
        with:
          install: true
          cache: true

      - name: Install dependencies
        run: mise run sync

      - name: Build
        run: mise run build

      - name: Test
        run: mise run test
